name: Build Executable
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller scikit-learn joblib
      - name: Build Executable with PyInstaller
        shell: bash
        run: |
          pyinstaller backend/model/main.py \
            --onefile \
            --name voice_assistant \
            --distpath dist \
            --clean \
            --noconfirm \
            --hidden-import sklearn \
            --hidden-import joblib \
            --add-data "backend/model/model1/model.pkl:backend/model/model1" \
            --add-data "backend/model/model1/vectorizer.pkl:backend/model/model1" \
            --add-data "backend/model/model2/model2.pkl:backend/model/model2" \
            --add-data "backend/model/model2/vectorizer2.pkl:backend/model/model2" \
            --add-data "backend/model/model4/model4.pkl:backend/model/model4" \
            --add-data "backend/model/model4/vectorizer4.pkl:backend/model/model4"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: voice-assistant-${{ runner.os }}
          path: dist/voice_assistant${{ runner.os == 'Windows' && '.exe' || '' }}
