name: Build and Release Executable
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller scikit-learn joblib
      - name: Build executable
        shell: bash
        run: |
          pyinstaller backend/model/main.py \
            --onefile \
            --name voice_assistant_${{ matrix.os }} \
            --distpath dist \
            --clean \
            --noconfirm \
            --hidden-import sklearn \
            --hidden-import joblib \
            --hidden-import importlib.resources \
            --hidden-import sklearn.utils._array_api \
            --hidden-import sklearn.utils.validation \
            --hidden-import sklearn.feature_extraction \
            --hidden-import sklearn.feature_extraction.text \
            --hidden-import sklearn.naive_bayes \
            --hidden-import scipy.stats \
            --hidden-import scipy.stats._sobol \
            --hidden-import numpy \
            --hidden-import nltk \
            --add-data "backend/model/model1/model.pkl:backend/model/model1" \
            --add-data "backend/model/model1/vectorizer.pkl:backend/model/model1" \
            --add-data "backend/model/model2/model2.pkl:backend/model/model2" \
            --add-data "backend/model/model2/vectorizer2.pkl:backend/model/model2" \
            --add-data "backend/model/model4/model4.pkl:backend/model/model4" \
            --add-data "backend/model/model4/vectorizer4.pkl:backend/model/model4"
      - name: Rename output binary
        run: |
          mkdir uploads
          mv dist/* uploads/voice_assistant_${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          files: uploads/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
